def stateandtimezone():
    states = [
        {"zone": "US/Alabama", "gmt": "(GMT-06:00)", "name": "Alabama"},
        {"zone": "US/Alaska", "gmt": "(GMT-09:00 (Alaska))", "name": "Alaska"},
        {"zone": "US/Arizona", "gmt": "(GMT-07:00)", "name": "Arizona"},
        {"zone": "US/Arkansas", "gmt": "(GMT-06:00)", "name": "Arkansas"},
        {"zone": "US/California", "gmt": "(GMT-08:00)", "name": "California"},
        {"zone": "US/Colorado", "gmt": "(GMT-07:00)", "name": "Colorado"},
        {"zone": "US/Connecticut", "gmt": "(GMT-05:00)", "name": "Connecticut"},
        {"zone": "US/Delaware", "gmt": "(GMT-05:00)", "name": "Delaware"},
        {"zone": "US/Florida", "gmt": "(GMT-05:00)", "name": "Florida"},
        {"zone": "US/Georgia", "gmt": "(GMT-05:00)", "name": "Georgia"},
        {"zone": "US/Hawaii", "gmt": "(GMT-10:00)", "name": "Hawaii"},
        {"zone": "US/Idaho", "gmt": "(GMT-07:00)", "name": "Idaho"},
        {"zone": "US/Illinois", "gmt": "(GMT-06:00)", "name": "Illinois"},
        {"zone": "US/Indiana", "gmt": "(GMT-05:00)", "name": "Indiana"},
        {"zone": "US/Iowa", "gmt": "(GMT-06:00)", "name": "Iowa"},
        {"zone": "US/Kansas", "gmt": "(GMT-06:00)", "name": "Kansas"},
        {"zone": "US/Kentucky", "gmt": "(GMT-05:00)", "name": "Kentucky"},
        {"zone": "US/Louisiana", "gmt": "(GMT-06:00)", "name": "Louisiana"},
        {"zone": "US/Maine", "gmt": "(GMT-05:00)", "name": "Maine"},
        {"zone": "US/Maryland", "gmt": "(GMT-05:00)", "name": "Maryland"},
        {"zone": "US/Massachusetts", "gmt": "(GMT-05:00)", "name": "Massachusetts"},
        {"zone": "US/Michigan", "gmt": "(GMT-05:00)", "name": "Michigan"},
        {"zone": "US/Minnesota", "gmt": "(GMT-06:00)", "name": "Minnesota"},
        {"zone": "US/Mississippi", "gmt": "(GMT-06:00)", "name": "Mississippi"},
        {"zone": "US/Missouri", "gmt": "(GMT-06:00)", "name": "Missouri"},
        {"zone": "US/Montana", "gmt": "(GMT-07:00)", "name": "Montana"},
        {"zone": "US/Nebraska", "gmt": "(GMT-06:00)", "name": "Nebraska"},
        {"zone": "US/Nevada", "gmt": "(GMT-08:00)", "name": "Nevada"},
        {"zone": "US/New_Hampshire", "gmt": "(GMT-05:00)", "name": "New Hampshire"},
        {"zone": "US/New_Jersey", "gmt": "(GMT-05:00)", "name": "New Jersey"},
        {"zone": "US/New_Mexico", "gmt": "(GMT-07:00)", "name": "New Mexico"},
        {"zone": "US/New_York", "gmt": "(GMT-05:00)", "name": "New York"},
        {"zone": "US/North_Carolina", "gmt": "(GMT-05:00)", "name": "North Carolina"},
        {"zone": "US/North_Dakota", "gmt": "(GMT-06:00)", "name": "North Dakota"},
        {"zone": "US/Ohio", "gmt": "(GMT-05:00)", "name": "Ohio"},
        {"zone": "US/Oklahoma", "gmt": "(GMT-06:00)", "name": "Oklahoma"},
        {"zone": "US/Oregon", "gmt": "(GMT-08:00)", "name": "Oregon"},
        {"zone": "US/Pennsylvania", "gmt": "(GMT-05:00)", "name": "Pennsylvania"},
        {"zone": "US/Rhode_Island", "gmt": "(GMT-05:00)", "name": "Rhode Island"},
        {"zone": "US/South_Carolina", "gmt": "(GMT-05:00)", "name": "South Carolina"},
        {"zone": "US/South_Dakota", "gmt": "(GMT-06:00)", "name": "South Dakota"},
        {"zone": "US/Tennessee", "gmt": "(GMT-06:00)", "name": "Tennessee"},
        {"zone": "US/Texas", "gmt": "(GMT-06:00)", "name": "Texas"},
        {"zone": "US/Utah", "gmt": "(GMT-07:00)", "name": "Utah"},
        {"zone": "US/Vermont", "gmt": "(GMT-05:00)", "name": "Vermont"},
        {"zone": "US/Virginia", "gmt": "(GMT-05:00)", "name": "Virginia"},
        {"zone": "US/Washington", "gmt": "(GMT-08:00)", "name": "Washington"},
        {"zone": "US/West_Virginia", "gmt": "(GMT-05:00)", "name": "West Virginia"},
        {"zone": "US/Wisconsin", "gmt": "(GMT-06:00)", "name": "Wisconsin"},
        {"zone": "US/Wyoming", "gmt": "(GMT-07:00)", "name": "Wyoming"}
    ]
    return states
