from tortoise.models import Model
from tortoise import fields

class Assistant(Model):
    id = fields.IntField(pk=True)
    vapi_assistant_id = fields.CharField(max_length=255, null=True)
    user = fields.ForeignKeyField("models.User", related_name="assistants")
    name = fields.CharField(max_length=255)
    provider = fields.CharField(max_length=255)
    first_message = fields.CharField(max_length=255)
    model = fields.CharField(max_length=255)
    systemPrompt = fields.TextField()
    knowledgeBase = fields.JSONField(null=True)  
    leadsfile = fields.JSONField(null=True)  
    temperature = fields.FloatField(null=True)
    maxTokens = fields.IntField(null=True)
    transcribe_provider = fields.CharField(max_length=255, null=True)
    transcribe_language = fields.CharField(max_length=255, null=True)
    transcribe_model = fields.CharField(max_length=255, null=True)
    voice_provider = fields.CharField(max_length=255, null=True)
    voice = fields.CharField(max_length=255, null=True)
    forwardingPhoneNumber = fields.CharField(max_length=255, null=True)
    endCallPhrases = fields.JSONField(null=True)  
    attached_Number = fields.CharField(max_length=255, null=True, default=None)
    vapi_phone_uuid = fields.CharField(max_length=255, null=True, default=None)
    draft = fields.BooleanField(null = True, default = False)   
    assistant_toggle = fields.BooleanField(null  = True) 
    success_evalution = fields.TextField(null=True)
    category= fields.TextField(null=True,default="contacting_lead")
    voice_model = fields.TextField(null=True,default="octave")
    languages = fields.JSONField(null=True)  
    created_at = fields.DatetimeField(auto_now_add=True)
    updated_at = fields.DatetimeField(auto_now=True)
    speed = fields.FloatField(null=True, default=1)
    stability = fields.FloatField(null=True, default=0.5)
    similarityBoost = fields.FloatField(null=True, default=0.75)
    # add_voice_id_manually = fields.BooleanField(default=False)
    # voice_id = fields.CharField(max_length=255, null=True)
